case:
  login: TestDatas\login_case.xlsx
path:
  log: Log\
  png: Png\
ims:
  storage:
    Admin-Auto-Token: aa
  url:
    login: aa
    main: http://ims-new.test.wangoon.cn/dashboard
wms:
  storage:
    Admin-Auto-Token: aa
  url:
    login: http://wms.test.wangoon.cn/login
    main: http://wms.test.wangoon.cn/dashboard
tms:
  storage:
    Admin-Auto-Token: 990094e7e715455dbad4945b8060a2fe
  url:
    login: http://auto.test.wangoon.cn/login
    main: http://auto.test.wangoon.cn/index
desired_caps:
  platformName: Android
  platformVersion: 7.1.2
  deviceName: 127.0.0.1:62001
  appPackage: plus.H56BFB035
  appActivity: io.dcloud.PandoraEntry
