case:
  login: TestDatas\login_case.xlsx
tms:
  path:
    log: Log\
    png: Png\
  storage:
    Admin-Auto-Token: 990094e7e715455dbad4945b8060a2fe
  url:
    login: http://auto.test.wangoon.cn/login
    main: http://auto.test.wangoon.cn/index
